**Task 1**

In [30]:
import pandas as pd

df = pd.read_csv("/content/vgsalesGlobale.csv")

totalsales = df["Global_Sales"].sum()
print(f"Total Global Sales: {totalsales:} million")

topgamesales = df["Global_Sales"].max()
topgame = df[df["Global_Sales"] == topgamesales].iloc[0]
print(f"Top Selling Game: {topgame['Name']} ({topgame['Global_Sales']} million)")

avgsales = df[["NA_Sales", "EU_Sales", "JP_Sales", "Other_Sales"]].mean()
print("Average Sales per Region:\n", avgsales)

topgenres = df.groupby("Genre")["Global_Sales"].sum().nlargest(5)
print("Top 5 Genres by Global Sales:\n", topgenres)

genresales = df.groupby("Genre")[["NA_Sales", "EU_Sales", "JP_Sales", "Other_Sales"]].sum()
print("Most Popular Genre in NA:", topNAgenre)

topNAgenresales = genresales["NA_Sales"].max()
print("Top 3 Platforms by Global Sales:\n", topplatforms)

lastrows = df.tail(10)
print("Last 10 Rows:\n", lastrows)
topNAgenre = genresales[genresales["NA_Sales"] == topNAgenresales].index[0]
topplatforms = df.groupby("Platform")["Global_Sales"].sum().nlargest(3)
marketshare = (df.groupby("Genre")["Global_Sales"].sum() / totalsales) * 100
print("Market Share per Genre (%):\n", marketshare)

correlation = df["NA_Sales"].corr(df["EU_Sales"])
print(f"Correlation between NA and EU Sales: {correlation:}")

Total Global Sales: 8920.44 million
Top Selling Game: Wii Sports (82.74 million)
Average Sales per Region:
 NA_Sales       0.264667
EU_Sales       0.146652
JP_Sales       0.077782
Other_Sales    0.048063
dtype: float64
Top 5 Genres by Global Sales:
 Genre
Action          1751.18
Sports          1330.93
Shooter         1037.37
Role-Playing     927.37
Platform         831.37
Name: Global_Sales, dtype: float64
Most Popular Genre in NA: Action
Top 3 Platforms by Global Sales:
 Platform
PS2     1255.64
X360     979.96
PS3      957.84
Name: Global_Sales, dtype: float64
Last 10 Rows:
         Rank                                               Name Platform  \
16588  16591                                   Mega Brain Boost       DS   
16589  16592  Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...      PSV   
16590  16593  Eiyuu Densetsu: Sora no Kiseki Material Collec...      PSP   
16591  16594                                Myst IV: Revelation       PC   
16592  16595                       

**TASK 2**

In [14]:
words = {
    "hello": "hola",
    "goodbye": "adiós",
    "thank you": "gracias",
    "water": "agua",
    "book": "libro"
}

while True:
    word = input("Enter an English word (or type 'exit' to stop): ")
    if word.lower() == 'exit':
     break
    if word in words:
        print(f"The Spanish translation is: {words[word]}")
    else:
        print("Translation is not available.")


Enter an English word (or type 'exit' to stop): hello
The Spanish translation is: hola
Enter an English word (or type 'exit' to stop): exit


**Task 3**

In [18]:
def classify_emails(emails):
    imp, promo, spam = [], [], []
    imp_keywords = ["meeting", "urgent", "project", "deadline"]
    promo_keywords = ["sale", "discount", "offer", "deal"]
    spam_keywords = ["win", "prize", "lottery", "free money"]

    for email in emails:
        email = email.lower()
        if any(word in email for word in imp_keywords): imp.append(email)
        elif any(word in email for word in promo_keywords): promo.append(email)
        elif any(word in email for word in spam_keywords): spam.append(email)

    return imp, promo, spam

emails = [
    "Urgent meeting scheduled for tomorrow.",
    "Limited time offer! Get 50% off on all items.",
    "Congratulations! You have won a lottery prize.",
    "Reminder: Project deadline is next week.",
    "Don't miss out on our exclusive discount deal!",
    "Click here to claim your free money now!"
]
imp_emails, promo_emails, spam_emails = classify_emails(emails)
print("Important:", imp_emails)
print("Promotions:", promo_emails)
print("Spam:", spam_emails)


Important: ['urgent meeting scheduled for tomorrow.', 'reminder: project deadline is next week.']
Promotions: ['limited time offer! get 50% off on all items.', "don't miss out on our exclusive discount deal!"]
Spam: ['congratulations! you have won a lottery prize.', 'click here to claim your free money now!']


**Task 4**

In [19]:
cart = []
prod = {
    1: "AI Response Simulator",
    2: "Investment Decision",
    3: "Market Analysis Tool"
}
print("Welcome to the Store!")
print("Available Products:")
for num, p in prod.items():
    print(f"{num}. {p}")

print("Enter 'q' to checkout.")

while True:
    choice = input("Enter product number: ")

    if choice.lower() == 'q':
        break

    if choice.isdigit():
        choice = int(choice)
        if choice in prod:
            cart.append(prod[choice])
            print(f"'{prod[choice]}' added to your cart.")
        else:
            print("Invalid choice.")
    else:
        print("Invalid input. Enter a number or 'q'.")

print("\nYour Cart:")
if cart:
    for item in cart:
        print(f"- {item}")
else:
    print("Your cart is empty.")

print("Thank you! Goodbye!")

Welcome to the Store!
Available Products:
1. AI Response Simulator
2. Investment Decision
3. Market Analysis Tool
Enter 'q' to checkout.
Enter product number: 1
'AI Response Simulator' added to your cart.
Enter product number: q

Your Cart:
- AI Response Simulator
Thank you! Goodbye!


**Task 5(a)**

In [21]:
import numpy as np

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

result = arr1 + arr2

print("Array 1:\n", arr1)
print("Array 2:\n", arr2)
print("Element-wise Addition Result:\n", result)


Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[ 7  8  9]
 [10 11 12]]
Element-wise Addition Result:
 [[ 8 10 12]
 [14 16 18]]


**Task 5(b)**

In [22]:
result = arr1 * arr2
print("Element-wise Product:\n", result)


Element-wise Product:
 [[ 7 16 27]
 [40 55 72]]


**Task 6(a)**

In [28]:
import numpy as np
arr1D = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr2D = arr1D.reshape(3, 4)
print("\nReshaped 2D Array (3x4):\n", arr2D)



Reshaped 2D Array (3x4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


**Task 6(b)**

In [32]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])
h_concat = np.concatenate((a, b), axis=1)
v_concat = np.concatenate((a, b), axis=0)

print("\nHorizontally Concatenated Array:\n", h_concat)
print("\nVertically Concatenated Array:\n", v_concat)



Horizontally Concatenated Array:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]

Vertically Concatenated Array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


**Task 7**

In [17]:
originallist = [1, 2, 3, 4, 5]
reversedlist = originallist[::-1]

print("Original List:", originallist)
print("Reversed List:", reversedlist)


Original List: [1, 2, 3, 4, 5]
Reversed List: [5, 4, 3, 2, 1]
